# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extractnomfromurlpb/extractnomfromurlpb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-extractnomfromurlpb/extractnomfromurlpb.proto\x12\nextractnom\",\n\x07\x41rticle\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x9c\x01\n\tLegalNorm\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cjurisdiction\x18\x03 \x01(\t\x12\x17\n\x0fprocedure_types\x18\x04 \x03(\t\x12%\n\x08\x61rticles\x18\x05 \x03(\x0b\x32\x13.extractnom.Article\x12\x16\n\x0e\x65\x66\x66\x65\x63tive_date\x18\x06 \x01(\t\"6\n\x11\x45xtractNomRequest\x12\x10\n\x08nom_name\x18\x01 \x01(\t\x12\x0f\n\x07nom_url\x18\x02 \x01(\t\"?\n\x12\x45xtractNomResponse\x12)\n\nlegal_norm\x18\x01 \x01(\x0b\x32\x15.extractnom.LegalNorm2b\n\x11\x45xtractNomService\x12M\n\nExtractNom\x12\x1d.extractnom.ExtractNomRequest\x1a\x1e.extractnom.ExtractNomResponse\"\x00\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extractnomfromurlpb.extractnomfromurlpb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _ARTICLE._serialized_start=61
  _ARTICLE._serialized_end=105
  _LEGALNORM._serialized_start=108
  _LEGALNORM._serialized_end=264
  _EXTRACTNOMREQUEST._serialized_start=266
  _EXTRACTNOMREQUEST._serialized_end=320
  _EXTRACTNOMRESPONSE._serialized_start=322
  _EXTRACTNOMRESPONSE._serialized_end=385
  _EXTRACTNOMSERVICE._serialized_start=387
  _EXTRACTNOMSERVICE._serialized_end=485
# @@protoc_insertion_point(module_scope)
