# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import extractnomfromurlpb_pb2 as extractnomfromurlpb_dot_extractnomfromurlpb__pb2


class ExtractNomServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractNom = channel.unary_unary(
            '/extractnom.ExtractNomService/ExtractNom',
            request_serializer=extractnomfromurlpb_dot_extractnomfromurlpb__pb2.ExtractNomRequest.SerializeToString,
            response_deserializer=extractnomfromurlpb_dot_extractnomfromurlpb__pb2.ExtractNomResponse.FromString,
        )


class ExtractNomServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractNom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtractNomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ExtractNom': grpc.unary_unary_rpc_method_handler(
            servicer.ExtractNom,
            request_deserializer=extractnomfromurlpb_dot_extractnomfromurlpb__pb2.ExtractNomRequest.FromString,
            response_serializer=extractnomfromurlpb_dot_extractnomfromurlpb__pb2.ExtractNomResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'extractnom.ExtractNomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ExtractNomService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractNom(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/extractnom.ExtractNomService/ExtractNom',
                                             extractnomfromurlpb_dot_extractnomfromurlpb__pb2.ExtractNomRequest.SerializeToString,
                                             extractnomfromurlpb_dot_extractnomfromurlpb__pb2.ExtractNomResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
